/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oraibekeres;
import java.util.Scanner;
import javax.swing.JOptionPane;
    
/**
 *
 * @author PolgárBotond(SZF_202
 */
public class bekerogui extends javax.swing.JFrame {
static Scanner scanner = new Scanner (System.in);
    /**
     * Creates new form bekerogui
     */
    public bekerogui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnev = new javax.swing.JLabel();
        lblkor = new javax.swing.JLabel();
        txtnev = new javax.swing.JTextField();
        txtkor = new javax.swing.JTextField();
        btnVeglegesit = new javax.swing.JButton();
        lblVisszajelzes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnev.setText("Add meg a neved: ");

        lblkor.setText("Add meg az életkorod: ");

        txtnev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnevActionPerformed(evt);
            }
        });

        txtkor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkorActionPerformed(evt);
            }
        });

        btnVeglegesit.setText("Véglegesítés");
        btnVeglegesit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeglegesitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVeglegesit)
                    .addComponent(lblVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblkor)
                            .addComponent(lblnev))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnev, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnev)
                    .addComponent(txtnev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkor)
                    .addComponent(txtkor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnVeglegesit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnevActionPerformed
        //int kor = 0;
        //System.out.println("Add meg az életkorod: ");
        //kor = scanner.nextInt();
    }//GEN-LAST:event_txtnevActionPerformed

    private void txtkorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkorActionPerformed
        //String nev = "";
        //System.out.println("Add meg a neved: ");
        //nev = scanner.nextLine();
    }//GEN-LAST:event_txtkorActionPerformed

    private void btnVeglegesitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeglegesitActionPerformed
        String beKor = txtkor.getText();
        String beNev = txtnev.getText();
        int kor = Integer.parseInt(beKor);
        boolean jo = kor > 6 && beNev.length() >= 3;
        if (!jo){
            String hiba = "Hibás, add meg újra";
            lblVisszajelzes.setText(hiba);
        }else{
            String vissza = "Neved: " + beNev + ", életkorod: " + beKor;
            lblVisszajelzes.setText(vissza);
        
            
            kor = kor + 1;
            JOptionPane.showMessageDialog(rootPane,"Szülinapod után a korod: " + " " + kor);
        } 
        
        
        
       
       
        
        
        
        
        
        
    }//GEN-LAST:event_btnVeglegesitActionPerformed

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bekerogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bekerogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bekerogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bekerogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bekerogui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVeglegesit;
    private javax.swing.JLabel lblVisszajelzes;
    private javax.swing.JLabel lblkor;
    private javax.swing.JLabel lblnev;
    private javax.swing.JTextField txtkor;
    private javax.swing.JTextField txtnev;
    // End of variables declaration//GEN-END:variables
}
